# Generated by Django 3.0.4 on 2020-04-21 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('nickname', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, choices=[('BBL', 'ธนาคารกรุงเทพ'), ('BBC', 'ธนาคารกรุงเทพพาณิชย์การ'), ('KTB', 'ธนาคารกรุงไทย'), ('BAY', 'ธนาคารกรุงศรีอยุธยา'), ('KBANK', 'ธนาคารกสิกรไทย'), ('CITI', 'ธนาคารซิตี้แบงค์'), ('TMB', 'ธนาคารทหารไทย'), ('SCB', 'ธนาคารไทยพาณิชย์'), ('NBANK', 'ธนาคารธนชาติ'), ('SICB', 'ธนาคารนครหลวงไทย'), ('GSB', 'ธนาคารออมสิน'), ('GHB', 'ธนาคารอาคารสงเคราะห์'), ('BAAC', 'ธ.ก.ส.')], max_length=5, null=True)),
                ('line', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Share_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('admin_frist', models.BooleanField(default=True, help_text='เท้าแชร์ยกหัว')),
                ('admin_last', models.BooleanField(default=False, help_text='เท้าแชร์หักค้ำท้าย')),
                ('date_receive_no_payment', models.BooleanField(default=True, help_text='หักวันรับ')),
                ('queue', models.BooleanField(default=False, help_text='รับตามมือจอง')),
                ('fix_rate', models.BooleanField(default=False, help_text='ฟิกเรต')),
                ('bit', models.BooleanField(default=False, help_text='บิท')),
                ('quantity', models.IntegerField(help_text='จำนวนมือ')),
                ('capital', models.IntegerField(blank=True, help_text='เงินต้น', null=True)),
                ('payment', models.IntegerField(blank=True, help_text='ส่งงวดละ', null=True)),
                ('interest', models.IntegerField(blank=True, help_text='ดอกต่องวด', null=True)),
                ('term', models.IntegerField(blank=True, help_text='จำนวนวันที่ส่งต่องวด', null=True)),
                ('fix_last_date', models.BooleanField(default=False, help_text='วันที่ส่งต้องลงท้ายตรงกัน')),
                ('date_run', models.DateField(help_text='วันที่เริ่มวง')),
                ('share_close', models.BooleanField(default=False, help_text='ปิดวง ไม่ต้องการให้แสดงผลแชร์วงนี้')),
                ('build_share_pay_date', models.BooleanField(default=True, help_text='แสดงปุมสร้างวันจ่ายแชร์')),
            ],
        ),
        migrations.CreateModel(
            name='Share_groups_customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_queue', models.IntegerField(blank=True, help_text='ลำดับที่', null=True)),
                ('fix_rate', models.IntegerField(blank=True, help_text='ฟิกเรต', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Customers')),
                ('share_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Share_groups')),
            ],
            options={
                'unique_together': {('share_group', 'receive_queue')},
            },
        ),
        migrations.CreateModel(
            name='Share_pay_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(help_text='วันที่ต้องส่ง')),
                ('share_groups_customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Share_groups_customers')),
            ],
        ),
    ]
