# Generated by Django 3.0.4 on 2020-04-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('nickname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('bank_account', models.CharField(max_length=20, null=True)),
                ('line', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
