# Generated by Django 3.0.4 on 2020-04-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_groups_customers',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.Customers'),
        ),
        migrations.AlterField(
            model_name='share_groups_customers',
            name='share_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.Share_groups'),
        ),
        migrations.AlterField(
            model_name='share_pay_date',
            name='share_groups_customers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.Share_groups_customers'),
        ),
    ]
