# Generated by Django 3.0.4 on 2020-04-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(choices=[('BBL', 'ธนาคารกรุงเทพ'), ('BBC', 'ธนาคารกรุงเทพพาณิชย์การ'), ('KTB', 'ธนาคารกรุงไทย'), ('BAY', 'ธนาคารกรุงศรีอยุธยา'), ('KBANK', 'ธนาคารกสิกรไทย'), ('CITI', 'ธนาคารซิตี้แบงค์'), ('TMB', 'ธนาคารทหารไทย'), ('SCB', 'ธนาคารไทยพาณิชย์'), ('NBANK', 'ธนาคารธนชาติ'), ('SICB', 'ธนาคารนครหลวงไทย'), ('GSB', 'ธนาคารออมสิน'), ('GHB', 'ธนาคารอาคารสงเคราะห์'), ('BAAC', 'ธ.ก.ส.')], max_length=5, null=True),
        ),
    ]
