# Generated by Django 3.0.4 on 2020-04-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_customer_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('BBL', 'ธนาคารกรุงเทพ'), ('BBC', 'ธนาคารกรุงเทพพาณิชย์การ'), ('KTB', 'ธนาคารกรุงไทย'), ('BAY', 'ธนาคารกรุงศรีอยุธยา'), ('KBANK', 'ธนาคารกสิกรไทย'), ('CITI', 'ธนาคารซิตี้แบงค์'), ('TMB', 'ธนาคารทหารไทย'), ('SCB', 'ธนาคารไทยพาณิชย์'), ('NBANK', 'ธนาคารธนชาติ'), ('SICB', 'ธนาคารนครหลวงไทย'), ('GSB', 'ธนาคารออมสิน'), ('GHB', 'ธนาคารอาคารสงเคราะห์'), ('BAAC', 'ธ.ก.ส.')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='line',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
