# Generated by Django 3.0.4 on 2020-04-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20200421_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_pay_date',
            name='pay_date',
            field=models.DateField(help_text='วันที่ต้องส่ง', null=True),
        ),
    ]
