# Generated by Django 3.0.4 on 2020-04-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20200416_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('capital', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('lesson', models.IntegerField()),
                ('date_run', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Share_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('admin_frist', models.BooleanField()),
                ('admin_last', models.BooleanField()),
                ('queue', models.BooleanField()),
                ('bit', models.BooleanField()),
            ],
        ),
    ]
