# Generated by Django 3.0.4 on 2020-04-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_share_groups_share_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Share_types',
        ),
        migrations.AddField(
            model_name='share_groups',
            name='admin_frist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='share_groups',
            name='admin_last',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='share_groups',
            name='bit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='share_groups',
            name='queue',
            field=models.BooleanField(default=True),
        ),
    ]
