# Generated by Django 3.0.4 on 2020-04-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20200421_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_groups_customers',
            name='receive_queue',
            field=models.IntegerField(default=1, help_text='ลำดับที่'),
        ),
    ]
