# Generated by Django 3.0.4 on 2020-04-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_auto_20200421_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share_groups_customers',
            name='date_bit',
        ),
        migrations.AddField(
            model_name='share_groups_customers',
            name='queue_bit',
            field=models.IntegerField(blank=True, help_text='ลำดับที่รับแชร์แบบบิท', null=True),
        ),
    ]
