# Generated by Django 3.0.4 on 2020-04-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_auto_20200416_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_groups',
            name='admin_frist',
            field=models.BooleanField(default=True, help_text='เท้าแชร์ยกหัว'),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='admin_last',
            field=models.BooleanField(default=True, help_text='เท้าแชร์หักค้ำท้าย'),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='bit',
            field=models.BooleanField(default=True, help_text='บิท'),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='capital',
            field=models.IntegerField(help_text='เงินต้น'),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='date_run',
            field=models.DateField(help_text='วันที่เริ่มวง'),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='interest',
            field=models.IntegerField(help_text='ดอกต่องวด'),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='lesson',
            field=models.IntegerField(help_text='จำนวนวันที่ส่ง'),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='payment',
            field=models.IntegerField(help_text='ส่งงวดละ'),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='quantity',
            field=models.IntegerField(help_text='จำนวนมือ'),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='queue',
            field=models.BooleanField(default=True, help_text='รับตามมือจอง'),
        ),
    ]
