# Generated by Django 3.0.4 on 2020-04-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_auto_20200416_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_groups',
            name='quantity',
            field=models.IntegerField(help_text='จำนวนมือ', max_length=30),
        ),
    ]
