# Generated by Django 3.0.4 on 2020-04-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_auto_20200416_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_groups',
            name='capital',
            field=models.IntegerField(blank=True, help_text='เงินต้น', null=True),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='interest',
            field=models.IntegerField(blank=True, help_text='ดอกต่องวด', null=True),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='lesson',
            field=models.IntegerField(blank=True, help_text='จำนวนวันที่ส่ง', null=True),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='payment',
            field=models.IntegerField(blank=True, help_text='ส่งงวดละ', null=True),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='quantity',
            field=models.IntegerField(help_text='จำนวนมือ'),
        ),
    ]
