# Generated by Django 3.0.4 on 2020-04-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_auto_20200422_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='share_groups_customers',
            name='receive_date',
            field=models.DateField(blank=True, help_text='วันที่เปียแชร์', null=True),
        ),
    ]
