# Generated by Django 3.0.4 on 2020-04-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_auto_20200416_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share_groups_customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Customers')),
                ('share_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Share_groups')),
            ],
        ),
    ]
