# Generated by Django 3.0.4 on 2020-04-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0011_share_groups_customers_receive_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share_pay_date',
            unique_together={('share_groups_customers', 'pay_date')},
        ),
    ]
