# Generated by Django 3.0.4 on 2020-04-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0013_auto_20200416_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share_groups',
            old_name='lesson',
            new_name='term',
        ),
    ]
