# Generated by Django 3.0.4 on 2020-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0014_auto_20200416_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_groups_customers',
            name='receive_queue',
            field=models.IntegerField(blank=True, help_text='ลำดับที่', null=True),
        ),
    ]
