# Generated by Django 3.0.4 on 2020-04-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0015_auto_20200416_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_groups',
            name='term',
            field=models.IntegerField(blank=True, help_text='จำนวนวันที่ส่งต่องวด', null=True),
        ),
    ]
