# Generated by Django 3.0.4 on 2020-04-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0016_auto_20200416_1716'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share_groups_customers',
            unique_together={('share_group', 'receive_queue')},
        ),
    ]
