# Generated by Django 3.0.4 on 2020-04-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Al_bum',
        ),
        migrations.RenameModel(
            old_name='Company',
            new_name='Au_thor',
        ),
        migrations.RenameModel(
            old_name='Author',
            new_name='Com_pany',
        ),
        migrations.RenameModel(
            old_name='Song',
            new_name='So_ng',
        ),
    ]
