# Generated by Django 3.0.4 on 2020-04-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200421_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='al_bum',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Au_thor'),
        ),
        migrations.AlterField(
            model_name='al_bum',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Com_pany'),
        ),
    ]
