# Generated by Django 3.0.4 on 2020-04-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_share_pay_date_interest_bit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share_pay_date',
            name='interest_bit',
        ),
        migrations.AddField(
            model_name='share_groups_customers',
            name='date_bit',
            field=models.DateField(help_text='วันที่รับแชร์แบบบิท', null=True),
        ),
        migrations.AddField(
            model_name='share_groups_customers',
            name='interest_bit',
            field=models.IntegerField(default=0, help_text='ดอกเบี้ยที่บิท'),
        ),
        migrations.AlterField(
            model_name='share_groups_customers',
            name='receive_queue',
            field=models.IntegerField(default=0, help_text='ลำดับที่'),
        ),
    ]
