# Generated by Django 3.0.4 on 2020-04-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_remove_share_groups_customers_queue_bit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_groups_customers',
            name='fix_rate',
            field=models.IntegerField(default=0, help_text='ฟิกเรต'),
        ),
    ]
