# Generated by Django 3.0.4 on 2020-04-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_auto_20200422_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_groups',
            name='interest',
            field=models.IntegerField(default=0, help_text='ดอกต่องวด'),
        ),
        migrations.AlterField(
            model_name='share_groups',
            name='payment',
            field=models.IntegerField(default=0, help_text='ส่งงวดละ'),
        ),
    ]
