# Generated by Django 3.0.4 on 2020-04-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_auto_20200423_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='nickname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
