# Generated by Django 3.0.4 on 2020-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0013_auto_20200423_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_groups',
            name='fix_last_date',
            field=models.BooleanField(default=False, help_text='วันที่ส่งต้องลงท้ายตรงกัน แชร์ราย10วันและ15วันต้องติ๊กตรงนี้ด้วย'),
        ),
        migrations.AlterField(
            model_name='share_groups_customers',
            name='fix_rate',
            field=models.IntegerField(default=0, help_text='ฟิกเรต ใส่เฉพาะวงแชร์แบบฟิกเรต'),
        ),
        migrations.AlterField(
            model_name='share_groups_customers',
            name='interest_bit',
            field=models.IntegerField(default=0, help_text='ดอกเบี้ยที่บิท ไม่ต้องใส่ โปรแกรมจะกำหนดให้อัตโนมัติ'),
        ),
        migrations.AlterField(
            model_name='share_groups_customers',
            name='receive_date',
            field=models.DateField(blank=True, help_text='วันที่เปียแชร์ ไม่ต้องใส่ โปรแกรมจะกำหนดให้อัตโนมัติ', null=True),
        ),
        migrations.AlterField(
            model_name='share_groups_customers',
            name='receive_queue',
            field=models.IntegerField(default=1, help_text='ลำดับที่ ต้องใส่ทุกครั้ง'),
        ),
    ]
